### ISSUE TITLE
Logout causes permission_denied errors

### ISSUE THREAD

**Issue by Fandekasp** [prescottprue/react-redux-firebase#494]
**Do you want to request a *feature* or report a *bug*?**  

(If this is a *usage question*, please **do not post it here**—post it on [gitter](https://gitter.im/redux-firebase/Lobby). If this is not a “feature” or a “bug”, or the phrase “How do I...?” applies, then it's probably a usage question.)
Bug related to #464

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
```es6
export const rrfConfig = {
  // react-redux-firebase config
  userProfile: "users",
  logErrors: false,
};
```

```es6
@connect(({firebase: {auth}}) => ({auth}))
export default class Header extends Component {
  static propTypes = {
    auth: PropTypes.shape(),
  };

  render() {
    return (
      <AppBar
        id="new-header"
        style={{position: "fixed"}}
        zDepth={0}
        iconElementLeft={<Logo />}
        iconStyleLeft={{margin: 0, position: "relative"}}
        iconElementRight={isEmpty(this.props.auth) ? <AnonymousMenu /> : <LoggedInMenu />}
        iconStyleRight={{margin: 0}}
      />
    );
  }
}
```
The AnonymousMenu will call a LoginForm component when button is pressed
```es6
@withFirebase
export default class LoginForm extends Component {
  static propTypes = {
    firebase: PropTypes.shape({
      login: PropTypes.func.isRequired,
    }).isRequired,
  };

  constructor(props) {
    super(props);
    this.doLogin = this.doLogin.bind(this);
  }

  doLogin = provider => () => {
    const credentials = {
      provider,
      type: "popup",
    };
    this.props.firebase.login(credentials);
  };
```
That isn't a listener trying to access /users/... data right?

The LoggedInMenu shows the user name and a logout button
```es6
@withFirebase
@connect(({firebase: {auth}}) => ({auth}))
export default class LoggedInMenu extends Component {
  static propTypes = {
    auth: PropTypes.shape(),
    firebase: PropTypes.shape({
      logout: PropTypes.func.isRequired,
    }).isRequired,
  };

  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick = () => {
    this.props.firebase.logout();
  };

  render() {
    return (
      <div className="logout">
        <span>{this.props.auth.displayName}</span>
        <FlatButton
          className="logout-btn"
          label="ログアウト"
          onClick={this.handleClick}
        />
      </div>
    );
  }
}
```
As soon as the logout promise is resolved, my Header will switch back to <AnonymousMenu />, so the error doesn't make sense to me. 
Setting logErrors to false didn't change anything

**What is the expected behavior?**
No error should be displayed.

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**
react-redux-firebase@2.1.5

**Comment by Fandekasp** [comment]
tried to add 
```
    if (isEmpty(this.props.auth)) {
      return false;
    }
```
at the top of my LoggedInMenu render method, in the assumption that component would be rendered faster than the Header one, but it didn't clear the error...

**Comment by prescottprue** [comment]
@Fandekasp To answer your question about "does this create a users listener" - yes. You have provided `userProfile: 'users'` to the RRF config - this will automatically manage profiles and write to the `'users'` path of the database.

Did you trying checking to see if auth data is loaded before rendering [as mentioned in the query docs](http://react-redux-firebase.com/docs/queries.html#loading)? It looks like you are accessing a parameter on `this.props.auth` before confirming it exists. `isEmpty` will return `false` until data has loaded, but it hasn't yet loaded.

What you want to do is first confirm that auth data is loaded, then you can check to see if it is empty or if values exist. This pattern is followed using `auth` in [the state based query example](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/snippets/stateBasedQuery).

All of this said, I will leave the issue open until we confirm that is what is going on. If so, I am open to changing the docs to make this more clear if you have any sugestions.

**Comment by Fandekasp** [comment]
@prescottprue to start with, you're awesome. Thank you for this first class support.

Honestly, I'm not 100% clear on the auth/profile differences yet. When using oauth services like google and facebook, `firebase.auth` will be prepopulated with a displayName that I could display. On the other side, login with email/password wouldn't display that name even if I adjusted the database entry to mimick the other services (eg redundant `uid.displayName` and `uid.providerData.0.displayName`). 
I finally found out that I need to use `firebase.profile` for email/password accounts, with `firebase.profile.displayName` being populated by `@@reactReduxFirebase/SET_PROFILE`
Since profiles also has the isLoaded and isEmpty methods, I'm wondering why would I need `firebase.auth` at all ? It's indeed a little bit slower to load the name for oauth users...

Full code:
```es6
import React, {Component} from "react";
import PropTypes from "prop-types";
import {connect} from "react-redux";
import FlatButton from "material-ui/FlatButton";
import {isEmpty, isLoaded, withFirebase} from "react-redux-firebase";

@withFirebase
@connect(({firebase: {profile}}) => ({profile}))
export default class MenuNew extends Component {
  static propTypes = {
    profile: PropTypes.shape({
      isEmpty: PropTypes.bool.isRequired,
      displayName: PropTypes.string,
    }),
    firebase: PropTypes.shape({
      logout: PropTypes.func.isRequired,
    }).isRequired,
  };

  static defaultProps = {
    profile: {displayName: "貴方"},
  };

  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    const {firebase} = this.props;
    firebase.logout();
  }

  render() {
    const {profile} = this.props;

    if (!isLoaded(profile)) {
      return <div>Loading...</div>;
    }

    return (
      <div className="logout">
        {!isEmpty(profile) && <span>{profile.displayName}</span>}
        <FlatButton
          className="logout-btn"
          label="ログアウト"
          onClick={this.handleClick}
        />
      </div>
    );
  }
}
```
The problem is I keep having the error on logout

I have the default rules for the `users` db table (Default security rules require users to be authenticated):
```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

settings:
```es6
export const rrfConfig = {
  // react-redux-firebase config
  userProfile: "users",
  logErrors: false,
};
```
As discussed above, I cannot leave userProfile off my config, or displayName would never be available for email/password users.

**Comment by Fandekasp** [comment]
Reading the code, I see that `logout` calls `unWatchUserProfile` in https://github.com/prescottprue/react-redux-firebase/blob/master/src/actions/auth.js#L548

but it must fail silently, since I'm receiving this "error with profile listener" error afterwards:
![](https://i.imgur.com/h7mHv0R.png)

**Comment by Fandekasp** [comment]
After reading http://react-redux-firebase.com/docs/queries.html , I tried to replace all occurences of `withFirebase` with `firebaseConnect()`  to automatically manage listeners. But the result is the same.

**Comment by prescottprue** [comment]
@Fandekasp The listeners for profile are handled in the background due to the `userProfile` config param. Any listeners created by `firebaseConnect` or `withFirebase` are for other data within the database.


I am not currently able to replicate, so is it possible to provide a repo to reproduce with? Or possibly your create store logic?

Though it is probably unrelated, something to note is that you may want your rules to look something more like:

```json
{
  "rules": {
    ".read": false,
    ".write": false,
    "users": {
      "$uid": {
        ".read": "auth !== null && $uid === auth.uid",
        ".write": "auth !== null && $uid === auth.uid",
      }
    }
  }
}
```

Notice that all of the data other than `users` is locked down, and the users collection has user specific rules using the wildcard.

**Comment by IruneItoiz** [comment]
I get exactly the same error, I'm afraid. App generated through the generator, using login and password as authentication, pulling profiles from "user" automatically.

**Comment by prescottprue** [comment]
@IruneItoiz The intention is for the profile to be pulled from user. 

Has anyone tried with v2.1.6? It seems like there wasn't any real issue other than that a console.error was not behind a `logErrors` flag. Did anyone see anything other than console logs (i.e. unexpected functionality)?

**Comment by Fandekasp** [comment]
Not getting anything other than console log errors. Also running 2.1.6.

**Comment by lhas2** [comment]
Hi people! I'm getting the same error. I already tried with `v2.1.6` and `v2.1.7`. Anyone knows a solution for this?

**Comment by lhas2** [comment]
Hi! I fixed here downgrading my version to `v2.0.7`. Unfortunately, this is not the best solution. @prescottprue do you have some tip for this?

Another solution could be disabling the automatic fetch for profile, but this will create a lot of rework for me, and don't have to much sense to do this because the lib should handle with this correctly.  :~

**Comment by Fandekasp** [comment]
I disabled profile fetching and only use firebase for auth, storing user
profiles in my backend db ^^'

**Comment by prescottprue** [comment]
To everyone: Just wanted to again mentioned that this is *a log*, not an actual error in functionality, so there is no real reason to downgrade.

@lhas2 Is there a reason that you are looking to downgrade? A fix should be up soon, but this shouldn't be impacting much other than then sending a message to the console.

@Fandekasp The example you provided doesn't do a "double connection", `withFirebase` just provides access to the firebase instance on props. The piece that sets up a profile listener is `userProfile: 'users'` being passed to config, guessing you know that now though since you disabled it 😆.

**Comment by prescottprue** [comment]
After some more investigation, it seems like it might be due to logging out before detaching the profile listener. It should still not be causing any issues, but still made the fix.

Going to include  it in the upcoming `next` release (v2.2.0-alpha). Thanks to everyone for reporting.

**Comment by prescottprue** [comment]
Fix released in [v2.2.0-alpha](https://github.com/prescottprue/react-redux-firebase/releases/tag/v2.2.0-alpha). I was able to get the profile listener errors to no longer appear when logging out.

As expected, it didn't seem to impact functionality. The listeners were still attached, but Firebase automatically manages detaching listeners on logout, so it was really just a reminder. 

Anyone should feel free to reach out if it doesn't work as expected 😄

**Comment by wallacepeng** [comment]
it seems still happen without latest version. But it is differennt. 

![image](https://user-images.githubusercontent.com/894641/44679466-e8a1dd00-a9ef-11e8-9c54-e1263529d5da.png)

there seems an async listener during logout.

**Comment by kadikraman** [comment]
Thanks @prescottprue v2.2.0-alpha fixes the issue for me. Are you planning to release it soon?

**Comment by prescottprue** [comment]
@kadikraman You should be able to install from the `@next` tag for now by using `npm i --save react-redux-firebase@next. That can also be used in your `package.json` for now.

Hoping to release to the `latest` branch in the next few days.

**Comment by JorgeMoralesLopez** [comment]
Hi, I'm having the same error when I log out, yesterday I put my security rules in firebase firestore, allow read, write: if request.auth.uid! = null; only possible to read and write if the user is logged in. I installed the version react-redux-firebase ":" ^ 2.2.0-alpha.3 "but the problem continues, with logErrors: false, the red screen does not appear but if warning in debugger.
Your library is wonderful, thank you for giving us this great resource ...
regards.

**Comment by idesignpixels** [comment]
I still get this problem in 2.2.6, In my case i want the user profile (/users[uid]) to be read only by user, could this be causing it?

**Comment by prescottprue** [comment]
@idesignpixels Yes it could be based on how you are logging in. Do you have `updateProfileOnLogin` set to false? Otherwise when trying to login you will be attempting to update the profile. If thats not it, then feel free to open a new issue with your exact use case

**Comment by idesignpixels** [comment]
I still get it on logout with the following config.
```
{ useFirestoreForProfile: true, userProfile: 'users', updateProfileOnLogin: false }
```

**Comment by prescottprue** [comment]
@idesignpixels Wondering if that is due to it being with firestore. Would you mind opening a new issue with all of your info so we can track solving it on there (this issue was for RTDB).
