### ISSUE TITLE
bug(HOCs): use of componentWillReceiveProps in HOCs cause warnings with 16.9.0

### ISSUE THREAD

**Issue by shevchenko0** [prescottprue/react-redux-firebase#755]
# **Bug report**

## **Steps**
Use firestoreConnect with react-redux-firebase@3.0.0-alpha.16 and react@16.9.0
Open your console to see the warnings

## **Expected Result**
No warnings should appear

## **Actual Result**
```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: FirestoreConnectWrapped(Connect(withI18nextTranslation(TranscriptsList)))
```
## **Version**
3.0.0-alpha.16

**Comment by prescottprue** [comment]
Wasn't able to go straight to `componentDidUpdate`, but that will most likely happen in the future to support v17 of react.

The warning is fixed in [the v3.0.0-beta release](https://github.com/prescottprue/react-redux-firebase/releases/tag/v3.0.0-beta).

**Comment by s4ek1389** [comment]
@prescottprue Still getting this warning when using Strict Mode in react: 17.0.1 and react-redux-firebase 3.7.0. Is there a way to fix it?

**Comment by prescottprue** [comment]
@s4ek1389 Can you open a new issue with the warning so we don't loose track

**Comment by LuisMerinoP** [comment]
I am getting the warning with "react": "^17.0.1" and "react-redux-firebase": "^3.10.0". Would an oppened issue and codesandbox share help??

**Comment by nicholas919** [comment]
any updates on this issue? i'm getting same warning too

**Comment by LuisMerinoP** [comment]
no updates. I opened a new [issue](https://github.com/prescottprue/react-redux-firebase/issues/1059) for this warning. Seems that you should live with it until the HOC is fixed, or use react hooks to link your component to firestore to get rid of the warning

**Comment by nicholas919** [comment]
great.. thanks for the advice @LuisMerinoP but i think im done with this, the documentation won't help much and still..  errors were keep appear on my console... it would be great to create my own npm package
